name: Test bugsnag-python against Python versions

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        tox-version: ['']
        dependencies: ['tox tox-factor']

        include:
          - os: ubuntu-18.04
            python-version: 3.3
            dependencies: '"virtualenv<16" "tox<=2.9.1" "pluggy<0.6.0" webtest'
          - os: ubuntu-18.04
            python-version: 3.4
            dependencies: '"tox<=3.14.0" tox-factor'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install ${{ matrix.dependencies }}

    - name: Run tests (not Python 3.3)
      run: |
        pyversion=${{ matrix.python-version }}
        TOXFACTOR=py${pyversion//./} tox
      if: matrix.python-version != 3.3

    - name: Run tests (Python 3.3)
      run: TOXENV=py33-test,py33-requests,py33-wsgi,py33-flask,py33-tornado tox
      if: matrix.python-version == 3.3
